#!/bin/bash
# GA4 Agent - Commandes disponibles

echo "📊 Agent Google Analytics 4 - Bijouterie Hidous"
echo "================================================="
echo ""
echo "✅ Configuration active :"
echo "  Property ID: 334819686"
echo "  Compte: neo-seo-agent@neo-488103.iam.gserviceaccount.com"
echo ""
echo "📋 Commandes disponibles :"
echo ""
echo "1. Rapport temps réel (30 derniers jours) :"
echo "   ga4-realtime"
echo ""
echo "2. Pages les plus vues :"
echo "   ga4-top-pages"
echo ""
echo "3. Sources de trafic :"
echo "   ga4-traffic-sources"
echo ""
echo "4. Rapport hebdomadaire complet :"
echo "   ga4-weekly-report"
echo ""
echo "5. Alertes automatiques :"
echo "   ga4-check-alerts"
echo ""
echo "💡 Utilisation :"
echo "   /data/workspace/ga4-agent.sh [commande]"
